# Generated by Django 2.0.6 on 2018-10-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssida_app', '0002_auto_20181005_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accelerometer_x', models.FloatField()),
                ('accelerometer_y', models.FloatField()),
                ('accelerometer_z', models.FloatField()),
                ('gyroscope_x', models.FloatField(null=True)),
                ('gyroscope_y', models.FloatField(null=True)),
                ('gyroscope_z', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='time of generation')),
            ],
            options={
                'verbose_name_plural': 'Live Positioning Data',
            },
        ),
        migrations.AddIndex(
            model_name='livedata',
            index=models.Index(fields=['device_id'], name='ssida_app_l_device__20e4fa_idx'),
        ),
        migrations.AddIndex(
            model_name='livedata',
            index=models.Index(fields=['latitude', 'longitude'], name='ssida_app_l_latitud_8cd40c_idx'),
        ),
    ]
