# Generated by Django 2.0.6 on 2018-10-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssida_app', '0003_auto_20181005_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('score', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'verbose_name_plural': 'Computed GEO Score Data',
            },
        ),
        migrations.AddIndex(
            model_name='scoredata',
            index=models.Index(fields=['latitude', 'longitude'], name='ssida_app_s_latitud_735747_idx'),
        ),
    ]
